name: Close stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    uses: eclipse-osgi-technology/.github/.github/workflows/reuse_all_stale_bot.yml@main
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}
