name: Java Build, Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: eclipse-osgi-technology/.github/.github/workflows/reuse_java_build_test.yml@main
